### PR TITLE
✨ Add `@Provide()` decorator

### PR DESCRIPTION
**Pull request by alecgibson**
This change adds a `@Provide()` decorator, which mirrors the existing `@Inject()` decorator.

### CODE REVIEW

**Comment by rdhelms** [comment]
@ruojianll Any thoughts on this?

**Comment by ruojianll** [comment]
Pending until v3 released.

**Review by ruojianll — CHANGES_REQUESTED** [review]
The decorator should be compatible with `@Component({provide:{}})`, like `@Setup`.
And build on v3 codebase.

**Comment by alecgibson** [comment]
Okay @ruojianll I've basically completely rewritten this PR:

- Can be used like `@Provide` or `@Provide('alias')`
- Restructured as a function similar to `data()`, with correct access to `this`
- `@Provide` merges with config from `@Component({provide: {}})`
- Rebased on v3 `master`
- More thorough testing, involving `mount()` and `@Inject`

**Comment by alecgibson** [comment]
(Build failure should be fixed by https://github.com/facing-dev/vue-facing-decorator/pull/76 )

**Pull request merged**
